# TODO: fill out this stuff if the project ever gains traction

github: # Replace with a single GitHub username
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective slug
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
ko_fi: # Replace with a single Ko-fi username
liberapay: # Replace with a single Liberapay username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']