name: Report a bug in Platform Blocks
description: Use this template to report issues with Platform Blocks packages or example apps. For questions, ideas, or feature requests, open a discussion instead.
labels:
  - bug
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting
      description: Help us triage efficiently by completing the checklist.
      options:
        - label: I have searched existing GitHub issues and discussions for similar reports.
          required: true
        - label: I am using the latest published version of the affected Platform Blocks packages (or I have a reproduction on the latest main branch).
          required: true
  - type: input
    id: version
    attributes:
      placeholder: "@platform-blocks/ui@1.0.0, @platform-blocks/charts@1.0.0"
      label: Which Platform Blocks package versions are in your project?
    validations:
      required: true
  - type: dropdown
    id: package
    attributes:
      label: Which area is affected?
      options:
        - "@platform-blocks/ui"
        - "@platform-blocks/charts"
        - Docs site (platform-blocks.com)
        - Example gallery / demos
        - Tooling (scripts, generators, configuration)
        - Other (please describe below)
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: What runtime or framework are you using?
      options:
        - "Expo (managed)"
        - "Expo (prebuild / bare)"
        - "React Native CLI"
        - "Next.js"
        - "Vite"
        - "Other (specify below)"
    validations:
      required: true
  - type: checkboxes
    id: platforms
    attributes:
      label: Where can you reproduce the issue?
      description: Select all platforms that are affected.
      options:
        - label: iOS
        - label: Android
        - label: Web
    validations:
      required: true
  - type: input
    id: platformVersions
    attributes:
      label: Platform / OS versions (optional)
      description: Share any relevant platform details (e.g., iOS 18.1 simulator, Android 15 physical device, Chrome 130).
      placeholder: "iOS 18.1, Android 15, Chrome 130"
  - type: dropdown
    id: browser
    attributes:
      label: In which browsers you can reproduce the issue?
      options:
        - "All"
        - "Chrome"
        - "Safari"
        - "Firefox"
        - "Edge"
        - "Other (specify below)"
        - "Not applicable (native-only issue)"
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what happened, expected behavior, and reproduction steps.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment details
      description: Include OS, Node.js version, bundler, and any relevant configuration overrides.
      placeholder: "macOS 14, Node 20.11, Expo SDK 51, TypeScript 5.4, custom Metro config"
  - type: input
    id: link
    attributes:
      label: Reproduction link (Snack, Expo Router demo, CodeSandbox, etc.)
      description: Issues without a minimal reproduction are harder to action and may be closed. Prefer public links that maintainers can open quickly.
  - type: textarea
    id: possibleFix
    attributes:
      label: Possible fix
  - type: checkboxes
    id: self-service
    attributes:
      label: Self-service
      description: We welcome pull requests! Review the contributing guide in `CONTRIBUTING.md` if you're up for helping with a fix.
      options:
        - label: I would be willing to implement a fix for this issue
