name: Share a community starter
description: Share a public repository that showcases Platform Blocks in a real project.
labels:
  - community template
body:
  - type: input
    id: link
    attributes:
      label: GitHub repository link
      placeholder: https://github.com/username/your-starter-repo
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What does this starter include?
      description: Highlight the tech stack, supported platforms (web, native, Expo), and anything unique about the setup.
      placeholder: "A React Native + Expo starter with Platform Blocks UI and Charts, preconfigured for iOS, Android, and web."
    validations:
      required: true
  - type: textarea
    id: instructions
    attributes:
      label: Setup instructions
      description: Give newcomers a quick start. Include environment requirements and the primary command to run the project.
      placeholder: "Requires Node 20. Run `pnpm install` then `pnpm dev`."