name: Report a docs or site issue
description: Flag typos, broken links, or confusing content on platform-blocks.com or related docs.
labels:
  - docs
body:
  - type: input
    id: link
    attributes:
      label: Link to the page where something is not right
      placeholder: https://platform-blocks.com/path/to/page
  - type: textarea
    id: quote
    attributes:
      label: What is wrong?
      placeholder: Describe the issue
    validations:
      required: true
  - type: checkboxes
    id: self-service
    attributes:
      label: Self-service
      description: You are welcome to submit a fix for this issue after it is reviewed.
      options:
        - label: I would be willing to implement a fix for this issue