import type { BrandName } from '@platform-blocks/ui';

export const FEATURED_BRANDS: BrandName[] = [
  'google',
  'facebook',
  'apple',
  'github',
  'x',
  'microsoft',
  'linkedin',
  'discord',
  'slack',
  'chrome',
  'openai',
  'spotify',
  'youtube'
];

export const ALL_BRANDS: BrandName[] = [
  'google',
  'galaxy-store',
  'facebook',
  'discord',
  'android',
  'apple',
  'applePodcasts',
  'app-store',
  'appgallery',
  'openai',
  'chrome',
  'chromeWebStore',
  'spotify',
  'github',
  'x',
  'microsoft',
  'linkedin',
  'slack',
  'youtube',
  'youtubeMusic',
  'mastercard',
  'visa',
  'reddit',
  'amazon',
  'amazonAppstore',
  'amazonMusic',
  'twitch',
  'tiktok',
  'npm',
  'paypal',
  'appleMusic',
  'soundcloud',
  'whatsapp',
  'telegram',
  'signal',
  'meta',
  'discover',
  'amex',
  'messenger',
  'instagram',
  'zoom',
];

export const SAMPLE_BRANDS: BrandName[] = FEATURED_BRANDS.slice(0, 6);

export const DARK_MODE_BRANDS: BrandName[] = ['apple', 'github', 'x'];
