name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: deploy-docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            docs/package-lock.json

      - name: Install dependencies (root)
        run: npm ci

      - name: Install dependencies (docs)
        run: npm ci
        working-directory: docs

      - name: Build Expo web bundle
        run: npm run build-web --workspace=docs
        env:
          EXPO_NO_TELEMETRY: "1"
          EXPO_PUBLIC_WEB_APP_ROOT: "/platform-blocks/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/dist
          force_orphan: true
